# wORKFLOW NAME
name: depl-auth-srv

# DEFINES THE TYPE OF EVENT
on:
  push:
    branches:
      - master
    paths:
      - '  BACKEND-API-SERVICE-PROVIDERS/auth/**'

# DEFINE A JOB
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd BACKEND-API-SERVICE-PROVIDERS/auth && docker build -t stalit/auth-srv .
      - run: docker login -u $DOCKER_USERNAME -P $DOCKER_PASSWORD
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push slalit/auth-srv
      - uses: digitalocean/actions-doctl@v2
        with:
          token: $DIGITALOCEAN_ACCESS_TOKEN
        env: 
            TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} 
      - run: doctl kubernetes cluster kubeconfig save ticketing
      # - run: cd infra/k8 && kubectl apply -f auth-srv-depl.yaml
      - run: kubectl rollout restart deployment auth-srv-depl
