name: depl-manifest

on:
  push:
    branches: 
      - master
    paths:
      - 'infra/k8s/**'
      
jobs:
  build:
    runs-on: ubuntu-lastest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/actions-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save ticketing
      - run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod

