# wORKFLOW NAME
name: depl-auth-srv

# DEFINES THE TYPE OF EVENT THAT WILL TRIGGER THIS WORKFLOW 
on:
  push:
    branches:
      - master
    paths:
      - '  BACKEND-API-SERVICE-PROVIDERS/auth/**'

# DEFINE A JOB
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd BACKEND-API-SERVICE-PROVIDERS/auth && docker build -t stalit/auth-srv .
      # Authenticate ourdelves on DOCKERHUB
      - run: docker login -u $DOCKER_USERNAME -P $DOCKER_PASSWORD
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push slalit/auth-srv
      - uses: digitalocean/actions-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }} 
          
      # Saves the KUBERNETES config and switch to the remote KUBERNETES context(ticketing) as the active context
      - run: doctl kubernetes cluster kubeconfig save ticketing
      # - run: cd infra/k8 && kubectl apply -f auth-srv-depl.yaml

      # tells the remote KUBERNETES to update and restart the deployment (auth-srv-depl) with the current docker image from DOCKERHUB
      - run: kubectl rollout restart deployment auth-srv-depl
